import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import '../Models/Api_5_Model.dart';

class API_Integration_5 extends StatefulWidget {
  const API_Integration_5({Key? key}) : super(key: key);

  @override
  State<API_Integration_5> createState() => _API_Integration_5State();
}

class _API_Integration_5State extends State<API_Integration_5> {

  List<Autogenerated> userList=[];

  Future<List<Autogenerated>> getUsers()async{
    final response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/users'));
    var data = jsonDecode(response.body.toString());
    if(response.statusCode==200){
      for(Map i in data){
        userList.add(Autogenerated.fromJson(data));
      }
      return userList;
    }
    else{
      return userList;
    }
  }

  @override
  Widget build(BuildContext context) {
    return  Scaffold(
          body: Container(
            child: Column(
              children: [
                Expanded(child: FutureBuilder(future: getUsers(),builder: (context,snapshot){
                  if(!snapshot.hasData){
                    Text('loading');
                  }
                  else{
                    return ListView.builder(
                        itemCount: userList.length,
                        itemBuilder: (context,index){
                          return Text(index.toString());
                        });
                  }
                },))
              ],
            ),
          )
    );
  }
}
